### ISSUE TITLE
support double data without "d" suffix

### ISSUE THREAD

**Issue by ismlsmile** [MinimineLP/dart-gson#3]
example:

import 'package:gson/gson.dart';

main()
{
  var a = gson.decode('{aa:1.1}');
  print(a);
}

error:
Unhandled exception:
type 'double' is not a subtype of type 'int'
#0      GsonDecoder.decodeNumber (package:gson/decoder.dart:230:31)
#1      GsonDecoder.decode (package:gson/decoder.dart:40:14)
#2      GsonDecoder.decodeMap (package:gson/decoder.dart:125:20)
#3      GsonDecoder.decode (package:gson/decoder.dart:25:14)
#4      Gson.decode (package:gson/gson.dart:80:20)
#5      main (file:///D:/Code/TestDart/bin/main.dart:5:16)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

**Comment by ismlsmile** [comment]
in decoder.dart, modify like this, it it ok?

      case "d":
        ret = new Double(num.parse(number));
        if (!p.ended) {
          p.skip();
        }
        break;
      default:
        if(number.indexOf(".") != -1)
        {
          ret = new Double(double.parse(number));
        }
        else
        {
          ret = new Integer(num.parse(number));
        }

        break;

**Comment by MinimineLP** [comment]
Yes, thank you, I was able to recreate the exception and your solution also fixes it, thank you very much, I will commit the solution.

Minimine
