### ISSUE TITLE
Can not update to latest version - version 0.1.5

### ISSUE THREAD

**Issue by huytower** [MinimineLP/dart-gson#5]
Hello,

Did you update your library as your quote :

`gson: ^0.1.5`

Since I get error here :

> Because flutter_nct depends on gson ^0.1.5 which doesn't match any versions, version solving failed.
pub get failed (1; Because flutter_nct depends on gson ^0.1.5 which doesn't match any versions, version solving failed.)

p/s : I upgrade from version 0.1.4.

**Comment by MinimineLP** [comment]
Hello,
The reason for that is, that 0.1.5 is not out already, but i already changed the version in the docs, use 0.1.4, I will publish 0.1.5 soon, it has just one bugfix at the moment and I dont want to publish a new version for every bug, that is the reason.

Thank you for your issue
Minimine
